### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Tux-Panik** [Neo23x0/munin#1]
Hi Florian,

You have an issue in your file "munin.py", line 35:

`MAL_SAHRE_API_KEY = '-'`
should become
`MAL_SHARE_API_KEY = '-'`

Regards,
Julien

**Comment by Neo23x0** [comment]
Fixed - thanks 

https://github.com/Neo23x0/munin/commit/3c84835a19d9637e1d9c185ce26b64fc04f1da7c
