### ISSUE TITLE
i can not  find ValhallaAPI(api_key)

### ISSUE THREAD

**Issue by victorgenus** [Neo23x0/munin#16]
Where can I find ValhallaAPI's api_key?
https://smash.gg/tournament/valhalla/register 
Registration is closed
You can contact an admin here
and
I got virustotal api_key from my profile. Why run the python to error
No Virustotal API Key set or wrong format

**Comment by rolandpg** [comment]
The test api key is all "1"s  but you have to buy the other API key.

**Comment by Neo23x0** [comment]
It's for customers only, see: https://github.com/Neo23x0/munin#valhalla
