### ISSUE TITLE
VT_reCAPTCHA issue

### ISSUE THREAD

**Issue by zappeee** [Neo23x0/munin#24]
Anyway I can rerun these that get this issue?

How much do I miss with this error?
Seems like it still gets how many checks as malicious.

**Comment by Neo23x0** [comment]
Yeah, it's a protection mechanism by Virustotal that cannot be evaded so far. 

You lose "only" the details about a sample like: file names, size, type

**Comment by zappeee** [comment]
Ok, thanks!
