### ISSUE TITLE
bind to 0.0.0.0 or specific IP

### ISSUE THREAD

**Issue by gyterpena** [Neo23x0/munin#26]
When run in web mode munin binds to 127.0.0.1, is there a way to bind to 0.0.0.0 or specific IP address/interface?

munin.py -i munin.ini --web -w 10088

**Comment by dfirale** [comment]
https://github.com/Neo23x0/munin/blob/master/munin.py#L1036

Bind it to 0.0.0.0 by simply modifying line 1036: 

`app.run(host = '0.0.0.0',port=int(args.w))`

**Comment by gyterpena** [comment]
thx, this works.
