### ISSUE TITLE
tool is getting stuck in processing lines

### ISSUE THREAD

**Issue by sonali-23** [Neo23x0/munin#29]
hi
i am using latest python version 3.8, and m trying to run  munin master which is getting stuck on processing lines and no data is fetching. i have also tried it to run on python version 2.7 
 is there any compatibility issue?

**Comment by Neo23x0** [comment]
Could you test it with the ./munin-demo.txt in the program folder?

**Comment by sonali-23** [comment]
yes i tried with munin-demo.txt but still it is not working. after processing lines no output is there.

**Comment by Neo23x0** [comment]
Did you run it with the `--debug` command line parameter?

**Comment by sonali-23** [comment]
its showing some error saying handeling above exception, another exception occured

**Comment by sonali-23** [comment]
earlier it was running perfectly but now its getting stuck on processing lines. m unable to figure out the root cause.

**Comment by Neo23x0** [comment]
I need to see the error messages.

**Comment by sonali-23** [comment]
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.virustotal.com', port=443): Max retries exceeded with url: /vtapi/v2/file/report?resource=08330cb236fdf4490d922cb8e445d9bf&apikey=46196db6a0d51636568f742eac0af11d8c65d825d871fc3d5bfa47a9ab8b0d5e (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "munin.py", line 337, in getVTInfo
    response_dict = requests.get(VT_REPORT_URL, params=parameters, proxies=PROXY).json()
  File "C:\Users\Sonali.Behera\Documents\python\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Sonali.Behera\Documents\python\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Sonali.Behera\Documents\python\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Sonali.Behera\Documents\python\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Sonali.Behera\Documents\python\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.virustotal.com', port=443): Max retries exceeded with url: /vtapi/v2/file/report?resource=08330cb236fdf4490d922cb8e445d9bf&apikey=46196db6a0d51636568f742eac0af11d8c65d825d871fc3d5bfa47a9ab8b0d5e (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)')))
i think proxy error is there and ssl certificate error.. but before when i was running the tool it didnt get stuck like this.
and also i changed the api key for VT , where it is again giving error :\like this : 
[E] No Virustotal API Key set or wrong format
    Include your API key in a custom config file and use munin.ini as a template

    More info:
    https://github.com/Neo23x0/munin#get-the-api-keys-used-by-munin

**Comment by sonali-23** [comment]
[+] 12 cache entries read from cache database: vt-hash-db.json
[+] You can interrupt the process by pressing CTRL+C without losing the already gathered information
[+] Found results CSV from previous run: check-results_check1.csv
[+] Appending results to file: check-results_check1.csv
[+] Processing 12 lines ...
Error while accessing CAPE

 1 / 12 > Unknown
HASH: 043602ea078e9e236880bf82a76f272f COMMENT:
RESULT: - / -


after multiple tries it is getting stuck here.

**Comment by Neo23x0** [comment]
The error messages says
> certificate verify failed: self signed certificate in certificate chain

It's most likely because someone turned on SSL interception on your web proxy.
