### ISSUE TITLE
munin-hosts.py no scan IP/Domains

### ISSUE THREAD

**Issue by lcn0** [Neo23x0/munin#30]
HI! After the update you cannot use munin hosts anymore, do not scan or process IP or domain;

![image](https://user-images.githubusercontent.com/29029438/72625617-dc415b80-3927-11ea-9ae9-04ba742a2f22.png)

If I activate debug mode, the following is displayed;
![image](https://user-images.githubusercontent.com/29029438/72625722-11e64480-3928-11ea-8a17-7ff5c63f3b9c.png)

The munin that checks hash is ok

**Comment by Neo23x0** [comment]
Which update? You're using version 0.3, but 0.18.1 is current.

**Comment by lcn0** [comment]
I used a version earlier than Kali and assumed that there was some change in my system currently 5.4.0-kali2-amd64 # 1 SMP Debian 5.4.8-1kali1 (2020-01-06) x86_64 GNU / Linux =::::::(

**Comment by Neo23x0** [comment]
I won't debug a version 0.3. I have no idea why it says "February 2019". 0.3 is much older. 
Please use the most current version and try again.

**Comment by lcn0** [comment]
Yes MUNIN.py is v: __VERSION__ = "0.18.1 July 2019" and MUNIN-HOST.py is __VERSION__ = "0.3 February 2019" my problem is with munin-host that does not scan, I have validated it from the repository. Is it mandatory to use MISP Key?

**Comment by lcn0** [comment]
Oh finally I could find my error, the api were not correctly configured in the munin-host.py file (line API KEYS), although if they were correct in the MUNIN.INI file, I assumed that was enough with it. Curious.

**Comment by hernanfila** [comment]
Hi! It happened to me the same. I had to manually add the Key in munin-host.py though its already included in the .ini file.  
Thank you
