### ISSUE TITLE
[Feature request] MALWARE bazaar by ABUSE.ch

### ISSUE THREAD

**Issue by wikijm** [Neo23x0/munin#35]
Hi,

Would you please consider integrate MALWARE bazaar API too?
https://bazaar.abuse.ch/api/#upload

Sincerely,
WikiJM

**Comment by ssnkhan** [comment]
@wikijm I've managed to get this incorporated, returns a line with the `signature`, `tags` and `first_seen` values. Not sure whether it is worthy of a PR, but happy to share.

**Comment by Neo23x0** [comment]
Available in v0.19
- includes option to download the samples `--download`
