### ISSUE TITLE
PyMISP is not Working

### ISSUE THREAD

**Issue by n3x77** [Neo23x0/munin#9]
Hi,

in the default munin.ini file the MISP-Url is put in between single quotes. This leads to the following error:
`File "pymisp/api.py", line 112, in __init__
    raise PyMISPError('Unable to connect to MISP ({}). Please make sure the API key and the URL are correct (http/https is required): {}'.format(self.root_url, e))
pymisp.exceptions.PyMISPError: Unable to connect to MISP ('https://demomisp.local/'). Please make sure the API key and the URL are correct (http/https is required): No connection adapters were found for ''https://demomisp.local//servers/getPyMISPVersion.json'
^C
`
Also the URL in the ini-file must end with an '/'

**Comment by Neo23x0** [comment]
Thx
